services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pyawmal
      POSTGRES_PASSWORD: pyawmal
      POSTGRES_DB: pyawmal
    ports:
      - '5432:5432'
    volumes:
      - pyawmal-pg:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pyawmal']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pyawmal-pg:
